"""Investment feature schema registry.

Defines InvestmentFeatureSpec frozen dataclass and FEATURE_SPECS dict for all
90-130 investment-dedicated features across 9 categories (D-05, D-16).

Each spec declares train_sources (OOF-safe) and infer_sources (production)
for dual-mode feature resolution (D-13, D-14).
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class InvestmentFeatureSpec:
    """Immutable specification for a single investment feature.

    Fields per D-16:
      name             -- stable output column name (must start with "if_")
      category         -- one of 9 categories in CATEGORY_ORDER
      dtype            -- target pandas dtype string
      train_sources    -- source columns for train mode (OOF-safe, D-13)
      infer_sources    -- source columns for infer mode (production, D-14)
      required         -- True = fail-fast on source absence (D-19)
      default_value    -- None for required; fallback for optional
      missing_indicator -- None for required; indicator column name for optional
      leakage_class    -- "safe", "oof_only", or "post_race"
      description      -- human-readable description
    """

    name: str
    category: str
    dtype: str
    train_sources: tuple[str, ...]
    infer_sources: tuple[str, ...]
    required: bool
    default_value: float | int | None
    missing_indicator: str | None
    leakage_class: str
    description: str

    def __post_init__(self) -> None:
        if not self.name.startswith("if_"):
            raise ValueError(
                f"InvestmentFeatureSpec.name must start with 'if_': {self.name}"
            )


# D-05: Category order (stable, determines column order in output)
CATEGORY_ORDER: tuple[str, ...] = (
    "model_prob",
    "market_prob",
    "model_market_gap",
    "race_relative",
    "odds_band",
    "late_odds",
    "ability_form",
    "course_pace",
    "uncertainty",
)


# ---------------------------------------------------------------------------
# Feature spec definitions per category
# ---------------------------------------------------------------------------

_MODEL_PROB_SPECS: tuple[InvestmentFeatureSpec, ...] = (
    # --- model_prob (8-12 cols) ---
    InvestmentFeatureSpec(
        name="if_p_win",
        category="model_prob",
        dtype="float64",
        train_sources=("p_win_oof",),
        infer_sources=("p_win_pred",),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="モデル予測確率 (単勝)",
    ),
    InvestmentFeatureSpec(
        name="if_e_return",
        category="model_prob",
        dtype="float64",
        train_sources=("e_return_win_pred",),
        infer_sources=("e_return_win_pred",),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="モデル予測払戻倍率 (単勝)",
    ),
    InvestmentFeatureSpec(
        name="if_ev_raw",
        category="model_prob",
        dtype="float64",
        train_sources=(),  # derived: if_p_win * if_e_return
        infer_sources=(),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="期待値 (raw): P * E(return)",
    ),
    InvestmentFeatureSpec(
        name="if_p_win_corrected",
        category="model_prob",
        dtype="float64",
        train_sources=("p_win_corrected",),
        infer_sources=("p_win_corrected",),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="EV補正済み確率",
    ),
    InvestmentFeatureSpec(
        name="if_ev_corrected",
        category="model_prob",
        dtype="float64",
        train_sources=("ev_win_corrected",),
        infer_sources=("ev_win_corrected",),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="EV補正済み期待値",
    ),
    InvestmentFeatureSpec(
        name="if_ev_calibrated",
        category="model_prob",
        dtype="float64",
        train_sources=("ev_win_corrected",),
        infer_sources=("ev_win_calibrated",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_ev_calibrated_missing",
        leakage_class="safe",
        description="Isotonic + band scale キャリブレーション済みEV",
    ),
    InvestmentFeatureSpec(
        name="if_p_win_final",
        category="model_prob",
        dtype="float64",
        train_sources=("p_win_corrected",),
        infer_sources=("p_win_final",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_p_win_final_missing",
        leakage_class="safe",
        description="Benter blend 済み確率",
    ),
    InvestmentFeatureSpec(
        name="if_edge_win",
        category="model_prob",
        dtype="float64",
        train_sources=(),  # derived: if_p_win_final * tanodds - 1.0
        infer_sources=(),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_edge_win_missing",
        leakage_class="safe",
        description="エッジ (Benter blend後): P_final * odds - 1",
    ),
    InvestmentFeatureSpec(
        name="if_p_ability",
        category="model_prob",
        dtype="float64",
        train_sources=("p_ability_win",),
        infer_sources=("p_ability_win",),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="AbilityModel 単勝確率",
    ),
    InvestmentFeatureSpec(
        name="if_p_ability_place",
        category="model_prob",
        dtype="float64",
        train_sources=("p_ability_place",),
        infer_sources=("p_ability_place",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_p_ability_place_missing",
        leakage_class="safe",
        description="AbilityModel 複勝確率",
    ),
)

_MARKET_PROB_SPECS: tuple[InvestmentFeatureSpec, ...] = (
    # --- market_prob (6-10 cols) ---
    InvestmentFeatureSpec(
        name="if_implied_prob",
        category="market_prob",
        dtype="float64",
        train_sources=("p_market_win_adj",),
        infer_sources=("p_market_win_adj",),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="市場implied確率 (1/tanodds or adjusted)",
    ),
    InvestmentFeatureSpec(
        name="if_popularity_rank",
        category="market_prob",
        dtype="float64",
        train_sources=("popularity_rank",),
        infer_sources=("popularity_rank",),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="人気順位",
    ),
    InvestmentFeatureSpec(
        name="if_overround",
        category="market_prob",
        dtype="float64",
        train_sources=("overround",),
        infer_sources=("overround",),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="オーバーランド (市場マージン)",
    ),
    InvestmentFeatureSpec(
        name="if_market_entropy",
        category="market_prob",
        dtype="float64",
        train_sources=("market_entropy",),
        infer_sources=("market_entropy",),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="市場エントロピー",
    ),
    InvestmentFeatureSpec(
        name="if_odds_skewness",
        category="market_prob",
        dtype="float64",
        train_sources=("odds_skewness",),
        infer_sources=("odds_skewness",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_odds_skewness_missing",
        leakage_class="safe",
        description="オッズ分布歪度",
    ),
    InvestmentFeatureSpec(
        name="if_implied_prob_hhi",
        category="market_prob",
        dtype="float64",
        train_sources=("implied_prob_hhi",),
        infer_sources=("implied_prob_hhi",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_implied_prob_hhi_missing",
        leakage_class="safe",
        description="implied確率HHI (市場集中度)",
    ),
)

_MODEL_MARKET_GAP_SPECS: tuple[InvestmentFeatureSpec, ...] = (
    # --- model_market_gap (10-16 cols) ---
    InvestmentFeatureSpec(
        name="if_logit_gap",
        category="model_market_gap",
        dtype="float64",
        train_sources=(),  # derived: logit(p_model) - logit(p_market)
        infer_sources=(),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="モデル-市場 logit差",
    ),
    InvestmentFeatureSpec(
        name="if_abs_logit_gap",
        category="model_market_gap",
        dtype="float64",
        train_sources=(),  # derived: abs(if_logit_gap)
        infer_sources=(),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="モデル-市場 logit差絶対値",
    ),
    InvestmentFeatureSpec(
        name="if_deviation_rank",
        category="model_market_gap",
        dtype="float64",
        train_sources=("deviation_rank",),
        infer_sources=("deviation_rank",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_deviation_rank_missing",
        leakage_class="safe",
        description="乖離順位",
    ),
    InvestmentFeatureSpec(
        name="if_deviation_zscore",
        category="model_market_gap",
        dtype="float64",
        train_sources=("deviation_zscore",),
        infer_sources=("deviation_zscore",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_deviation_zscore_missing",
        leakage_class="safe",
        description="乖離Z-score",
    ),
    InvestmentFeatureSpec(
        name="if_odds_ability_ratio",
        category="model_market_gap",
        dtype="float64",
        train_sources=("odds_to_ability_ratio",),
        infer_sources=("odds_to_ability_ratio",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_odds_ability_ratio_missing",
        leakage_class="safe",
        description="オッズ/能力比",
    ),
    InvestmentFeatureSpec(
        name="if_edge_rank_in_race",
        category="model_market_gap",
        dtype="float64",
        train_sources=(),  # derived: rank(if_logit_gap) in race
        infer_sources=(),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="レース内エッジ順位",
    ),
    InvestmentFeatureSpec(
        name="if_edge_zscore_in_race",
        category="model_market_gap",
        dtype="float64",
        train_sources=(),  # derived: zscore(if_logit_gap) in race
        infer_sources=(),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_edge_zscore_in_race_missing",
        leakage_class="safe",
        description="レース内エッジZ-score",
    ),
    InvestmentFeatureSpec(
        name="if_signed_log_error",
        category="model_market_gap",
        dtype="float64",
        train_sources=("signed_log_error_win",),
        infer_sources=("signed_log_error_win",),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="MarketModel 符号付きlog誤差",
    ),
    InvestmentFeatureSpec(
        name="if_abs_log_error",
        category="model_market_gap",
        dtype="float64",
        train_sources=("abs_log_error_win",),
        infer_sources=("abs_log_error_win",),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="MarketModel 絶対log誤差",
    ),
    InvestmentFeatureSpec(
        name="if_market_error_rank",
        category="model_market_gap",
        dtype="float64",
        train_sources=("market_error_rank_in_race",),
        infer_sources=("market_error_rank_in_race",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_market_error_rank_missing",
        leakage_class="safe",
        description="レース内市場誤差順位",
    ),
    InvestmentFeatureSpec(
        name="if_top3_gap",
        category="model_market_gap",
        dtype="float64",
        train_sources=(),  # derived: gap to top3 logit_gap in race
        infer_sources=(),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_top3_gap_missing",
        leakage_class="safe",
        description="レース内top3とのエッジgap",
    ),
    InvestmentFeatureSpec(
        name="if_field_ev_dispersion",
        category="model_market_gap",
        dtype="float64",
        train_sources=(),  # derived: std(if_ev_corrected) in race
        infer_sources=(),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_field_ev_dispersion_missing",
        leakage_class="safe",
        description="レース内EV分散",
    ),
)

_RACE_RELATIVE_SPECS: tuple[InvestmentFeatureSpec, ...] = (
    # --- race_relative (12-18 cols) ---
    InvestmentFeatureSpec(
        name="if_p_win_race_rank",
        category="race_relative",
        dtype="float64",
        train_sources=(),  # derived: rank(if_p_win) in race
        infer_sources=(),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="レース内確率順位 (pct)",
    ),
    InvestmentFeatureSpec(
        name="if_ev_race_rank",
        category="race_relative",
        dtype="float64",
        train_sources=(),  # derived: rank(if_ev_corrected) in race
        infer_sources=(),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="レース内EV順位 (pct)",
    ),
    InvestmentFeatureSpec(
        name="if_p_ability_win",
        category="race_relative",
        dtype="float64",
        train_sources=("p_ability_win",),
        infer_sources=("p_ability_win",),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="AbilityModel単勝確率 (順位化はPhase 39で実装)",
    ),
    InvestmentFeatureSpec(
        name="if_ev_top1_gap",
        category="race_relative",
        dtype="float64",
        train_sources=(),  # derived: gap to top1 EV in race
        infer_sources=(),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_ev_top1_gap_missing",
        leakage_class="safe",
        description="レース内EV top1とのgap",
    ),
    InvestmentFeatureSpec(
        name="if_ev_top3_indicator",
        category="race_relative",
        dtype="float64",
        train_sources=(),  # derived: 1 if ev_race_rank <= 3
        infer_sources=(),
        required=False,
        default_value=0.0,
        missing_indicator="if_ev_top3_indicator_missing",
        leakage_class="safe",
        description="レース内EV top3指標",
    ),
    InvestmentFeatureSpec(
        name="if_form_trend_race_rank",
        category="race_relative",
        dtype="float64",
        train_sources=("form_trend_race_rank",),
        infer_sources=("form_trend_race_rank",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_form_trend_race_rank_missing",
        leakage_class="safe",
        description="フォームトレンド順位",
    ),
    InvestmentFeatureSpec(
        name="if_blood_wr_race_rank",
        category="race_relative",
        dtype="float64",
        train_sources=("blood_total_wr_race_rank",),
        infer_sources=("blood_total_wr_race_rank",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_blood_wr_race_rank_missing",
        leakage_class="safe",
        description="血統勝率順位",
    ),
    InvestmentFeatureSpec(
        name="if_closing_index_race_rank",
        category="race_relative",
        dtype="float64",
        train_sources=("closing_index_avg",),
        infer_sources=("closing_index_avg",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_closing_index_race_rank_missing",
        leakage_class="safe",
        description="末脚指数順位",
    ),
    InvestmentFeatureSpec(
        name="if_p_win_gap_to_fav",
        category="race_relative",
        dtype="float64",
        train_sources=(),  # derived: gap to favorite's p_win
        infer_sources=(),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_p_win_gap_to_fav_missing",
        leakage_class="safe",
        description="1番人気との確率gap",
    ),
    InvestmentFeatureSpec(
        name="if_field_strength_mean",
        category="race_relative",
        dtype="float64",
        train_sources=("p_ability_win",),
        infer_sources=("p_ability_win",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_field_strength_mean_missing",
        leakage_class="safe",
        description="レース内能力平均",
    ),
    InvestmentFeatureSpec(
        name="if_field_strength_std",
        category="race_relative",
        dtype="float64",
        train_sources=("p_ability_win",),
        infer_sources=("p_ability_win",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_field_strength_std_missing",
        leakage_class="safe",
        description="レース内能力標準偏差",
    ),
    InvestmentFeatureSpec(
        name="if_n_horses",
        category="race_relative",
        dtype="float64",
        train_sources=("rl_n_horses",),
        infer_sources=("rl_n_horses",),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="出走頭数",
    ),
)

_ODDS_BAND_SPECS: tuple[InvestmentFeatureSpec, ...] = (
    # --- odds_band (6-10 cols) ---
    InvestmentFeatureSpec(
        name="if_odds_band_id",
        category="odds_band",
        dtype="float64",
        train_sources=("tanodds",),
        infer_sources=("tanodds",),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="単勝オッズ (バンド変換はPhase 39で実装)",
    ),
    InvestmentFeatureSpec(
        name="if_odds",
        category="odds_band",
        dtype="float64",
        train_sources=("tanodds",),
        infer_sources=("tanodds",),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="単勝オッズ",
    ),
    InvestmentFeatureSpec(
        name="if_odds_log",
        category="odds_band",
        dtype="float64",
        train_sources=(),  # derived: log(if_odds)
        infer_sources=(),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_odds_log_missing",
        leakage_class="safe",
        description="log(単勝オッズ)",
    ),
    InvestmentFeatureSpec(
        name="if_odds_band_median_ev",
        category="odds_band",
        dtype="float64",
        train_sources=(),  # derived: median(if_ev_corrected) by band
        infer_sources=(),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_odds_band_median_ev_missing",
        leakage_class="safe",
        description="オッズ帯内中央EV",
    ),
    InvestmentFeatureSpec(
        name="if_odds_band_count",
        category="odds_band",
        dtype="float64",
        train_sources=(),  # derived: count by band in race
        infer_sources=(),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_odds_band_count_missing",
        leakage_class="safe",
        description="オッズ帯内頭数",
    ),
    InvestmentFeatureSpec(
        name="if_odds_band_ev_rank",
        category="odds_band",
        dtype="float64",
        train_sources=(),  # derived: rank(if_ev_corrected) within band
        infer_sources=(),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_odds_band_ev_rank_missing",
        leakage_class="safe",
        description="オッズ帯内EV順位",
    ),
)

_LATE_ODDS_SPECS: tuple[InvestmentFeatureSpec, ...] = (
    # --- late_odds (8-12 cols) ---
    InvestmentFeatureSpec(
        name="if_odds_drop_60_10",
        category="late_odds",
        dtype="float64",
        train_sources=("odds_drop_rate_60_10",),
        infer_sources=("odds_drop_rate_60_10",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_odds_drop_60_10_missing",
        leakage_class="safe",
        description="60分→10分オッズ下落率",
    ),
    InvestmentFeatureSpec(
        name="if_odds_drop_30_10",
        category="late_odds",
        dtype="float64",
        train_sources=("odds_drop_rate_30_10",),
        infer_sources=("odds_drop_rate_30_10",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_odds_drop_30_10_missing",
        leakage_class="safe",
        description="30分→10分オッズ下落率",
    ),
    InvestmentFeatureSpec(
        name="if_odds_velocity",
        category="late_odds",
        dtype="float64",
        train_sources=("odds_velocity",),
        infer_sources=("odds_velocity",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_odds_velocity_missing",
        leakage_class="safe",
        description="オッズ変化速度",
    ),
    InvestmentFeatureSpec(
        name="if_odds_volatility",
        category="late_odds",
        dtype="float64",
        train_sources=("odds_volatility",),
        infer_sources=("odds_volatility",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_odds_volatility_missing",
        leakage_class="safe",
        description="オッズボラティリティ",
    ),
    InvestmentFeatureSpec(
        name="if_odds_acceleration",
        category="late_odds",
        dtype="float64",
        train_sources=("odds_acceleration",),
        infer_sources=("odds_acceleration",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_odds_acceleration_missing",
        leakage_class="safe",
        description="オッズ加速度",
    ),
    InvestmentFeatureSpec(
        name="if_odds_direction_consistency",
        category="late_odds",
        dtype="float64",
        train_sources=("odds_direction_consistency",),
        infer_sources=("odds_direction_consistency",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_odds_direction_consistency_missing",
        leakage_class="safe",
        description="オッズ方向一貫性",
    ),
    InvestmentFeatureSpec(
        name="if_late_money_ratio",
        category="late_odds",
        dtype="float64",
        train_sources=(),  # derived: drop_30_10 / drop_60_10
        infer_sources=(),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_late_money_ratio_missing",
        leakage_class="safe",
        description="直前資金比率",
    ),
    InvestmentFeatureSpec(
        name="if_popularity_change",
        category="late_odds",
        dtype="float64",
        train_sources=("popularity_change_30_10",),
        infer_sources=("popularity_change_30_10",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_popularity_change_missing",
        leakage_class="safe",
        description="人気変動",
    ),
)

_ABILITY_FORM_SPECS: tuple[InvestmentFeatureSpec, ...] = (
    # --- ability_form (15-25 cols) ---
    InvestmentFeatureSpec(
        name="if_norm_finish_avg",
        category="ability_form",
        dtype="float64",
        train_sources=("norm_finish_logit_avg",),
        infer_sources=("norm_finish_logit_avg",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_norm_finish_avg_missing",
        leakage_class="safe",
        description="正規化着順平均 (logit)",
    ),
    InvestmentFeatureSpec(
        name="if_haron_zscore",
        category="ability_form",
        dtype="float64",
        train_sources=("harontimel5_zscore",),
        infer_sources=("harontimel5_zscore",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_haron_zscore_missing",
        leakage_class="safe",
        description="ハロンタイムZ-score",
    ),
    InvestmentFeatureSpec(
        name="if_closing_index",
        category="ability_form",
        dtype="float64",
        train_sources=("closing_index_avg",),
        infer_sources=("closing_index_avg",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_closing_index_missing",
        leakage_class="safe",
        description="末脚指数",
    ),
    InvestmentFeatureSpec(
        name="if_form_trend",
        category="ability_form",
        dtype="float64",
        train_sources=("form_trend",),
        infer_sources=("form_trend",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_form_trend_missing",
        leakage_class="safe",
        description="フォームトレンド",
    ),
    InvestmentFeatureSpec(
        name="if_form_consistency",
        category="ability_form",
        dtype="float64",
        train_sources=("form_consistency",),
        infer_sources=("form_consistency",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_form_consistency_missing",
        leakage_class="safe",
        description="フォーム一貫性",
    ),
    InvestmentFeatureSpec(
        name="if_blood_surface_wr",
        category="ability_form",
        dtype="float64",
        train_sources=("blood_surface_wr",),
        infer_sources=("blood_surface_wr",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_blood_surface_wr_missing",
        leakage_class="safe",
        description="血統サーフェス勝率",
    ),
    InvestmentFeatureSpec(
        name="if_blood_total_wr",
        category="ability_form",
        dtype="float64",
        train_sources=("blood_total_wr",),
        infer_sources=("blood_total_wr",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_blood_total_wr_missing",
        leakage_class="safe",
        description="血統総合勝率",
    ),
    InvestmentFeatureSpec(
        name="if_sire_wr",
        category="ability_form",
        dtype="float64",
        train_sources=("sire_wr",),
        infer_sources=("sire_wr",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_sire_wr_missing",
        leakage_class="safe",
        description="種牡馬勝率",
    ),
    InvestmentFeatureSpec(
        name="if_jockey_wr",
        category="ability_form",
        dtype="float64",
        train_sources=("jockey_wr_overall",),
        infer_sources=("jockey_wr_overall",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_jockey_wr_missing",
        leakage_class="safe",
        description="騎手勝率",
    ),
    InvestmentFeatureSpec(
        name="if_trainer_wr",
        category="ability_form",
        dtype="float64",
        train_sources=("trainer_wr_overall",),
        infer_sources=("trainer_wr_overall",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_trainer_wr_missing",
        leakage_class="safe",
        description="調教師勝率",
    ),
    InvestmentFeatureSpec(
        name="if_jt_combo_wr",
        category="ability_form",
        dtype="float64",
        train_sources=("jt_combo_wr",),
        infer_sources=("jt_combo_wr",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_jt_combo_wr_missing",
        leakage_class="safe",
        description="騎手-調教師コンビ勝率",
    ),
    InvestmentFeatureSpec(
        name="if_class_level",
        category="ability_form",
        dtype="float64",
        train_sources=("class_level_current",),
        infer_sources=("class_level_current",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_class_level_missing",
        leakage_class="safe",
        description="クラスレベル",
    ),
    InvestmentFeatureSpec(
        name="if_weighted_recent_form",
        category="ability_form",
        dtype="float64",
        train_sources=("weighted_recent_form_finish",),
        infer_sources=("weighted_recent_form_finish",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_weighted_recent_form_missing",
        leakage_class="safe",
        description="重み付き近走フォーム",
    ),
    InvestmentFeatureSpec(
        name="if_grade_x_form",
        category="ability_form",
        dtype="float64",
        train_sources=("grade_x_form_trend",),
        infer_sources=("grade_x_form_trend",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_grade_x_form_missing",
        leakage_class="safe",
        description="グレードxフォーム交互作用",
    ),
    InvestmentFeatureSpec(
        name="if_distance_x_closing",
        category="ability_form",
        dtype="float64",
        train_sources=("distance_x_closing_index",),
        infer_sources=("distance_x_closing_index",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_distance_x_closing_missing",
        leakage_class="safe",
        description="距離x末脚交互作用",
    ),
    InvestmentFeatureSpec(
        name="if_dm_time_rank",
        category="ability_form",
        dtype="float64",
        train_sources=("dm_time_rank",),
        infer_sources=("dm_time_rank",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_dm_time_rank_missing",
        leakage_class="safe",
        description="ダミータイム順位",
    ),
    InvestmentFeatureSpec(
        name="if_class_move",
        category="ability_form",
        dtype="float64",
        train_sources=("class_move",),
        infer_sources=("class_move",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_class_move_missing",
        leakage_class="safe",
        description="クラス変動",
    ),
)

_COURSE_PACE_SPECS: tuple[InvestmentFeatureSpec, ...] = (
    # --- course_pace (10-18 cols) ---
    InvestmentFeatureSpec(
        name="if_closing_speed_ratio",
        category="course_pace",
        dtype="float64",
        train_sources=("closing_speed_ratio_avg",),
        infer_sources=("closing_speed_ratio_avg",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_closing_speed_ratio_missing",
        leakage_class="safe",
        description="末脚速度比",
    ),
    InvestmentFeatureSpec(
        name="if_haron_race_gap",
        category="course_pace",
        dtype="float64",
        train_sources=("haron_race_gap_avg",),
        infer_sources=("haron_race_gap_avg",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_haron_race_gap_missing",
        leakage_class="safe",
        description="ハロンレースギャップ",
    ),
    InvestmentFeatureSpec(
        name="if_pace_ratio",
        category="course_pace",
        dtype="float64",
        train_sources=("pace_ratio_avg",),
        infer_sources=("pace_ratio_avg",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_pace_ratio_missing",
        leakage_class="safe",
        description="ペース比",
    ),
    InvestmentFeatureSpec(
        name="if_surface",
        category="course_pace",
        dtype="float64",
        train_sources=("surface",),
        infer_sources=("surface",),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="サーフェス (芝/ダート, 数値化)",
    ),
    InvestmentFeatureSpec(
        name="if_distance_bin",
        category="course_pace",
        dtype="float64",
        train_sources=("distance_bin",),
        infer_sources=("distance_bin",),
        required=True,
        default_value=None,
        missing_indicator=None,
        leakage_class="safe",
        description="距離ビン",
    ),
    InvestmentFeatureSpec(
        name="if_grade_code",
        category="course_pace",
        dtype="float64",
        train_sources=("grade_code",),
        infer_sources=("grade_code",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_grade_code_missing",
        leakage_class="safe",
        description="グレードコード",
    ),
    InvestmentFeatureSpec(
        name="if_track_condition",
        category="course_pace",
        dtype="float64",
        train_sources=("track_condition_code",),
        infer_sources=("track_condition_code",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_track_condition_missing",
        leakage_class="safe",
        description="馬場状態コード",
    ),
    InvestmentFeatureSpec(
        name="if_course_wr",
        category="course_pace",
        dtype="float64",
        train_sources=("course_wr",),
        infer_sources=("course_wr",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_course_wr_missing",
        leakage_class="safe",
        description="コース勝率",
    ),
    InvestmentFeatureSpec(
        name="if_pace_aptitude",
        category="course_pace",
        dtype="float64",
        train_sources=("pace_aptitude",),
        infer_sources=("pace_aptitude",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_pace_aptitude_missing",
        leakage_class="safe",
        description="ペース適性",
    ),
    InvestmentFeatureSpec(
        name="if_haron_zscore_trend",
        category="course_pace",
        dtype="float64",
        train_sources=("haron_zscore_trend",),
        infer_sources=("haron_zscore_trend",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_haron_zscore_trend_missing",
        leakage_class="safe",
        description="ハロンZ-score傾向",
    ),
    InvestmentFeatureSpec(
        name="if_pace_early",
        category="course_pace",
        dtype="float64",
        train_sources=("pace_early_avg",),
        infer_sources=("pace_early_avg",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_pace_early_missing",
        leakage_class="safe",
        description="前半ペース",
    ),
    InvestmentFeatureSpec(
        name="if_pace_late",
        category="course_pace",
        dtype="float64",
        train_sources=("pace_late_avg",),
        infer_sources=("pace_late_avg",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_pace_late_missing",
        leakage_class="safe",
        description="後半ペース",
    ),
    InvestmentFeatureSpec(
        name="if_closing_speed_race_rank",
        category="course_pace",
        dtype="float64",
        train_sources=("closing_speed_ratio_avg_race_rank",),
        infer_sources=("closing_speed_ratio_avg_race_rank",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_closing_speed_race_rank_missing",
        leakage_class="safe",
        description="末脚速度比順位",
    ),
)

_UNCERTAINTY_SPECS: tuple[InvestmentFeatureSpec, ...] = (
    # --- uncertainty (10-16 cols) ---
    InvestmentFeatureSpec(
        name="if_conformal_lower",
        category="uncertainty",
        dtype="float64",
        train_sources=("EV_lower_win_corrected",),
        infer_sources=("EV_lower_win_corrected",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_conformal_lower_missing",
        leakage_class="safe",
        description="Conformal EV下限",
    ),
    InvestmentFeatureSpec(
        name="if_conformal_upper",
        category="uncertainty",
        dtype="float64",
        train_sources=("EV_upper_win_corrected",),
        infer_sources=("EV_upper_win_corrected",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_conformal_upper_missing",
        leakage_class="safe",
        description="Conformal EV上限",
    ),
    InvestmentFeatureSpec(
        name="if_conformal_width",
        category="uncertainty",
        dtype="float64",
        train_sources=(),  # derived: upper - lower
        infer_sources=(),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_conformal_width_missing",
        leakage_class="safe",
        description="Conformal区間幅",
    ),
    InvestmentFeatureSpec(
        name="if_conformal_score",
        category="uncertainty",
        dtype="float64",
        train_sources=("conformal_confidence_score",),
        infer_sources=("conformal_confidence_score",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_conformal_score_missing",
        leakage_class="safe",
        description="Conformal信頼スコア",
    ),
    InvestmentFeatureSpec(
        name="if_p_x_e_interaction",
        category="uncertainty",
        dtype="float64",
        train_sources=("p_x_e_interaction",),
        infer_sources=("p_x_e_interaction",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_p_x_e_interaction_missing",
        leakage_class="safe",
        description="P*E交互作用",
    ),
    InvestmentFeatureSpec(
        name="if_p_minus_e_gap",
        category="uncertainty",
        dtype="float64",
        train_sources=("p_minus_e_gap",),
        infer_sources=("p_minus_e_gap",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_p_minus_e_gap_missing",
        leakage_class="safe",
        description="P-E gap",
    ),
    InvestmentFeatureSpec(
        name="if_ev_uncertainty_ratio",
        category="uncertainty",
        dtype="float64",
        train_sources=(),  # derived: width / ev_corrected
        infer_sources=(),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_ev_uncertainty_ratio_missing",
        leakage_class="safe",
        description="EV不確実性比率 (width/EV)",
    ),
    InvestmentFeatureSpec(
        name="if_market_log_error",
        category="uncertainty",
        dtype="float64",
        train_sources=("market_log_error_win",),
        infer_sources=("market_log_error_win",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_market_log_error_missing",
        leakage_class="safe",
        description="市場log誤差",
    ),
    InvestmentFeatureSpec(
        name="if_calibration_residual",
        category="uncertainty",
        dtype="float64",
        train_sources=("isotonic_residual_win",),
        infer_sources=("isotonic_residual_win",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_calibration_residual_missing",
        leakage_class="safe",
        description="Isotonicキャリブレーション残差",
    ),
    InvestmentFeatureSpec(
        name="if_odds_to_ability_dispersion",
        category="uncertainty",
        dtype="float64",
        train_sources=("odds_to_ability_ratio",),
        infer_sources=("odds_to_ability_ratio",),
        required=False,
        default_value=float("nan"),
        missing_indicator="if_odds_to_ability_dispersion_missing",
        leakage_class="safe",
        description="オッズ/能力比分散 (race内std)",
    ),
)

# ---------------------------------------------------------------------------
# FEATURE_SPECS: master dict of all specs
# ---------------------------------------------------------------------------

FEATURE_SPECS: dict[str, InvestmentFeatureSpec] = {
    spec.name: spec
    for spec in (
        *_MODEL_PROB_SPECS,
        *_MARKET_PROB_SPECS,
        *_MODEL_MARKET_GAP_SPECS,
        *_RACE_RELATIVE_SPECS,
        *_ODDS_BAND_SPECS,
        *_LATE_ODDS_SPECS,
        *_ABILITY_FORM_SPECS,
        *_COURSE_PACE_SPECS,
        *_UNCERTAINTY_SPECS,
    )
}


def _build_all_if_columns() -> list[str]:
    """Build ordered column list from FEATURE_SPECS in CATEGORY_ORDER."""
    columns: list[str] = []
    for cat in CATEGORY_ORDER:
        for spec in FEATURE_SPECS.values():
            if spec.category == cat:
                columns.append(spec.name)
    return columns


ALL_IF_COLUMNS: list[str] = _build_all_if_columns()
